spring.application.name=ProyectoCRUDRepository
spring.datasource.url=jdbc:mysql://localhost/adat8
spring.datasource.username=anonimo
spring.datasource.password=${DB_PASSWORD}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
